export const sampleProject: any = [
  {
    id: 1,
    name: 'Rimba Raya Biodiversity Reserve Project',
    description: 'The Rimba Raya Biodiversity Reserve Project, an initiative by InfiniteEARTH, aims to reduce Indonesia’s emissions by preserving some 64,000 hectares of tropical peat swamp forest.',
    credits: '169.360,8 credits available',
    verifier: 'Verra',
    country: 'Indonesia',
    rating: 'BeZero Carbon Rating AAA',
    purpose: 'Agriculture Forestry and Other Land Use',
    year: 2014,
  },
  {
    id: 2,
    name: 'Rimba Raya Biodiversity Reserve Project',
    description: 'The Rimba Raya Biodiversity Reserve Project, an initiative by InfiniteEARTH, aims to reduce Indonesia’s emissions by preserving some 64,000 hectares of tropical peat swamp forest.',
    credits: '169.360,8 credits available',
    verifier: 'Verra',
    country: 'Indonesia',
    rating: 'BeZero Carbon Rating AAA',
    purpose: 'Agriculture Forestry and Other Land Use',
    year: 2014,
  },
  {
    id: 3,
    name: 'Rimba Raya Biodiversity Reserve Project',
    description: 'The Rimba Raya Biodiversity Reserve Project, an initiative by InfiniteEARTH, aims to reduce Indonesia’s emissions by preserving some 64,000 hectares of tropical peat swamp forest.',
    credits: '169.360,8 credits available',
    verifier: 'Verra',
    country: 'Indonesia',
    rating: 'BeZero Carbon Rating AAA',
    purpose: 'Agriculture Forestry and Other Land Use',
    year: 2014,
  },
  {
    id: 4,
    name: 'Rimba Raya Biodiversity Reserve Project',
    description: 'The Rimba Raya Biodiversity Reserve Project, an initiative by InfiniteEARTH, aims to reduce Indonesia’s emissions by preserving some 64,000 hectares of tropical peat swamp forest.',
    credits: '169.360,8 credits available',
    verifier: 'Verra',
    country: 'Indonesia',
    rating: 'BeZero Carbon Rating AAA',
    purpose: 'Agriculture Forestry and Other Land Use',
    year: 2014,
  },
  {
    id: 5,
    name: 'Rimba Raya Biodiversity Reserve Project',
    description: 'The Rimba Raya Biodiversity Reserve Project, an initiative by InfiniteEARTH, aims to reduce Indonesia’s emissions by preserving some 64,000 hectares of tropical peat swamp forest.',
    credits: '169.360,8 credits available',
    verifier: 'Verra',
    country: 'Indonesia',
    rating: 'BeZero Carbon Rating AAA',
    purpose: 'Agriculture Forestry and Other Land Use',
    year: 2014,
  },
  {
    id: 6,
    name: 'Rimba Raya Biodiversity Reserve Project',
    description: 'The Rimba Raya Biodiversity Reserve Project, an initiative by InfiniteEARTH, aims to reduce Indonesia’s emissions by preserving some 64,000 hectares of tropical peat swamp forest.',
    credits: '169.360,8 credits available',
    verifier: 'Verra',
    country: 'Indonesia',
    rating: 'BeZero Carbon Rating AAA',
    purpose: 'Agriculture Forestry and Other Land Use',
    year: 2014,
  },
  {
    id: 7,
    name: 'Rimba Raya Biodiversity Reserve Project',
    description: 'The Rimba Raya Biodiversity Reserve Project, an initiative by InfiniteEARTH, aims to reduce Indonesia’s emissions by preserving some 64,000 hectares of tropical peat swamp forest.',
    credits: '169.360,8 credits available',
    verifier: 'Verra',
    country: 'Indonesia',
    rating: 'BeZero Carbon Rating AAA',
    purpose: 'Agriculture Forestry and Other Land Use',
    year: 2014,
  },
  {
    id: 8,
    name: 'Rimba Raya Biodiversity Reserve Project',
    description: 'The Rimba Raya Biodiversity Reserve Project, an initiative by InfiniteEARTH, aims to reduce Indonesia’s emissions by preserving some 64,000 hectares of tropical peat swamp forest.',
    credits: '169.360,8 credits available',
    verifier: 'Verra',
    country: 'Indonesia',
    rating: 'BeZero Carbon Rating AAA',
    purpose: 'Agriculture Forestry and Other Land Use',
    year: 2014,
  },
];
